CREATE DATABASE Clientes;
use Clientes;

CREATE TABLE estudiante (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	rut INT(9),
	edad INT(3),
	direccion VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
